# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
# TODO: Separate configurations for each environment

THUMB_SIZE: 32
SMALL_SIZE: 64
MEDIUM_SIZE: 100
LARGE_SIZE: 210
FULL_SIZE: 500

PERCENT_FEE: 3
STATIC_FEE_CENTS: 50

CHAT_LIMIT: 1
CHAT_MSG_PER_PAGE: 15

# Time in seconds between updating WePay account balances
BALANCE_UPDATE: 600
# After updating their balance, the user must wait this amount of time (seconds) before updating again, to prevent brute force
BALANCE_UPDATE_MINIMUM: 60

# In milliseconds
CHAT_LIMIT: 1000
CHAT_POLLING: 5000

GMAIL_DOMAIN: paywith.me
GMAIL_USERNAME: noreply@paywith.me
GMAIL_PASSWORD: U6Cq7j*L!!

SENDGRID_DOMAIN: paywith.me
SENDGRID_USERNAME: paywithme
SENDGRID_PASSWORD: 1Wearesocool

ORDRIN_KEY: J5gDVgJZwfXS--mc37V_l1yLY-vC1c3aNfvx6TByslo
ORDRIN_SECRET: f1GcQvXue6kqNlDBISD9SqHnD9q1yaIv14gCXq7ZALY

BALANCED_MARKETPLACE: TEST-MP2edcOz75u0cdKsDK7FWcFG
BALANCED_SECRET: 492415eecd9611e295b7026ba7d31e6f

RACKSPACE_KEY: 441e6ae0fb2aa44eb6c81af9cfc8a7bb
RACKSPACE_USERNAME: paywithme
RACKSPACE_URL: storage101.ord1.clouddrive.com

NUDGE_LIMIT: 3